filebeat.inputs: []

filebeat.modules:
  - module: suricata
    eve:
      enabled: true
      var.paths: ["/var/log/suricata/eve.json"]

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

processors:
  - add_tags:
      tags: ["lab-net"]
